### ISSUE TITLE
Some (most) embeds with video don't seem to be working. Strangely, they (sometimes) work if set to translate.

### ISSUE THREAD

**Issue by dziban303** [dangeredwolf/FixTweet#16]
* When trying to post a tweet with video using `pxtwitter`, `fxtwitter`, and `twittpr` domains, frequently nothing happens:
![image](https://user-images.githubusercontent.com/7931765/182260743-e438b741-0539-4aef-872e-e22516331e32.png)

* But they _do_ work if an ISO language code is tacked on the end to translate them:
![image](https://user-images.githubusercontent.com/7931765/182260860-3f125860-c5df-4545-9121-54e89b1a4885.png)

* With the important exception of adding `/en` to a tweet already in English: this does ***not*** work. Strangely, though, adding a *nonsense* language code will cause the embed to function correctly and display the tweet in English:
![image](https://user-images.githubusercontent.com/7931765/182261066-bc14bf9c-18d1-4e87-87b0-fa9b42af66be.png)

* This behavior when trying to translate to the language the tweet is written in does not appear to extend to other languages. This tweet was written in Ukrainian; trying to translate it to `uk` just posts it normally:
![image](https://user-images.githubusercontent.com/7931765/182261481-4ff2a979-6785-4e3d-9216-0cb5b66923ea.png)

* Also, embeds seem to work when extracting the video with the `d.` subdomain:
![image](https://user-images.githubusercontent.com/7931765/182261787-4ae86c98-839c-494a-a84f-97869b5d9ee8.png)

* Tweets without video/gifs seem to work, including those with quoted tweets, still images, and multiple images. 
* Sometimes nothing works:
![image](https://user-images.githubusercontent.com/7931765/182262511-ffb876a9-fb53-4593-8194-2284463dfe0b.png)

**Comment by dangeredwolf** [comment]
Just pushed out a commit to fix this. There are actually 2 separate problems (inadvertently caused by my rewrite separating API code from embed rendering) which causes this weird behavior where it works in translation and does not work outside of translation.

1. A cap of the length of the "author" text for the video was not being enforced, which meant really long tweets that happen to contain videos become borked. Because we replace t.co links  with their originals, this meant it was a lot easier to exhaust this limit
2. Translated Tweets actually did not have the t.co replacer working. That's my bad too! And it was something I noticed while diagnosing this issue
