### ISSUE TITLE
JSON API includes escaped html entities

### ISSUE THREAD

**Issue by cendyne** [dangeredwolf/FixTweet#24]
Example https://api.fxtwitter.com/RachelTobac/status/1554444909993607170

```json
{"code":200,"message":"OK","tweet":{"url":"https://twitter.com/RachelTobac/status/1554444909993607170",
"id":"1554444909993607170",
"text":"*ANNOUNCEMENT*\nPresenting: the trailer for our new 🎶MUSICAL🎶 &amp; spoken Security Awareness Videos! After the infosec sea shanty, dozens of teams DM’d me saying \"The song worked! MFA usage up, reporting way up, pls make more songs!\" So we got to work &amp; you all it's finally here!🤖","...":null}}
```

I would expect the text to not include `&amp;` but `&`

**Comment by dangeredwolf** [comment]
Good point and something I overlooked--Twitter API is giving us these escaped characters but I never bothered converting them back before because when we only operated as an embed service it didn't make a difference--but it does for the API. My solution is to convert these characters into the raw counterparts, and if need be we escape them for the HTML content.

**Comment by dangeredwolf** [comment]
I believe I've fixed it, but if you're seeing any other characters Twitter is escaping that we aren't restoring, please reopen the issue
