### ISSUE TITLE
More suggestions for comparison table

### ISSUE THREAD

**Issue by Deer-Spangle** [dangeredwolf/FixTweet#8]
Hey there, have you considered adding twitter64.com and ayytwitter.com to your comparison table?
I'm not sure where the source code is for the former, but the latter is https://github.com/StormyDragon/TwitFix

**Comment by dangeredwolf** [comment]
I've never heard of either of these. StormyDragon's TwitFix fork looks interesting in that it seems dockerable but otherwise I'n not aware of any end-user feature differences between it and TwitFix. Being dockerable is a nice feature, but TwitFix has 92 different forks and I can't possibly accommodate all in a single table. So I guess my benchmark is that either it must be popular or it must have significant enough improvements that there is considerable end-user feature additions. Related, I think it's a bit redundant having too many forks of the same thing in a feature compare graph: Twxtter is closer to original TwitFix and vxTwitter has some stuff taken out and added combining images as an option. If there's a fork of TwitFix with a significantly different enough feature set to differentiate it, I might consider it, but otherwise I just don't think it's relevant for most people.

**Comment by dangeredwolf** [comment]
again though if like there's a TwitFix fork or something similar that has a better feature set I might consider it though

**Comment by Deer-Spangle** [comment]
There were a few end-user differences early on, for sure. (Though, I think at first it was mostly a lot of back-end improvements). It had videos with descriptions, which the original TwitFix did not have, and I've seen it used on telegram quite a lot.
I recognise you can't add all of them! But those two are ones I have seen around a lot. Though I'm still totally lost on what twitter64.com does differently

**Comment by Deer-Spangle** [comment]
Ah, yeah, twitter64 is this person:
https://twitter.com/MegaKeon/status/1525970296666202113
https://twitter.com/MegaKeon/status/1525971975767728128
And it's just a deployment of vxtwitter by the sounds of it! (But with a 3d env on the homepage, rather than a link to any source)

So yeah, that can definitely be omitted
