### ISSUE TITLE
`<meta name=...>` and `<meta property=...>` used inconsistently

### ISSUE THREAD

**Issue by sfan5** [dangeredwolf/FixTweet#84]
I stumbled upon this because I have a regex that parses HTML (_yes I know_), probably low-priority since other people use real parsers.
Example:
```html
<meta name="og:image" content="https://pbs.twimg.com/media/FUBKu4QXoAAqMIL.jpg"/>
[...] <meta content="jack (@jack)" property="og:title"/>
```

[Mozilla documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta) suggests only `name` is valid while the [Opengraph spec](https://ogp.me/) consistently uses `property`.
I'd suggest consistently using the latter.

**Comment by dangeredwolf** [comment]
Yeah I've been meaning to make those consistent but I just didn't get around to it as yeah it didn't really affect very many people. So I will fix that. 

I will note that if you're trying to only parse FixTweet responses and are not just making a general purpose embed tool I would suggest looking at FixTweet's status Fetch API which returns the same data we use to make embeds but in an easily parseable JSON form. Basically you can get it by using api.fxtwitter.con instead of fxtwitter.com on links.

https://github.com/dangeredwolf/FixTweet/wiki/Status-Fetch-API
